"""Shared BenchmarkLookup protocol-conformance assertions, run against the
committed real-data fixture (data/seed/chargemaster_test_extract.json +
data/seed/medicare_rates.json) by BOTH apps/api/tests/test_lookup_sqlite.py
and apps/api/tests/test_lookup_supabase.py, so the two backends are proven
to return identical shapes/values from the same underlying data.

Expected values below were read directly off the committed fixture files
(not invented) — see the docstring in each assertion for how to recompute
them if the fixture is ever regenerated by scripts/build_chargemaster_fixture.py
or scripts/fetch_medicare.py.

NOTE: this file is named to avoid pytest collection (no `test_` prefix) —
it's a helper module, not a test module itself.
"""
from __future__ import annotations

BWH = "Brigham and Women's Hospital"
MGH = "Massachusetts General Hospital"


def run_conformance_checks(lookup) -> None:
    """lookup: any BenchmarkLookup implementation, backed by the mini
    chargemaster fixture (real ~217-row extract + 2 synthetic noise rows)."""

    # -- hospitals() — all 3 real hospitals present in the extract --------
    hospitals = lookup.hospitals()
    assert set(hospitals) == {
        BWH, MGH, "Newton-Wellesley Hospital",
    }, f"unexpected hospitals(): {hospitals}"

    # -- gross_charge / cash_price — constant per (hospital, code) --------
    # 36415 (venipuncture) @ BWH: gross_charge=$16.00, cash_price=$12.00 for
    # every payer row in the source extract (chargemaster_test_extract.json).
    assert lookup.gross_charge(BWH, "36415") == 16.0
    assert lookup.cash_price(BWH, "36415") == 12.0

    # unknown code -> None, never a crash or an invented number
    assert lookup.gross_charge(BWH, "00000") is None
    assert lookup.cash_price(BWH, "00000") is None

    # -- code_in_chargemaster ----------------------------------------------
    assert lookup.code_in_chargemaster(BWH, "36415") is True
    assert lookup.code_in_chargemaster(BWH, "00000") is False

    # -- plan_rate: exact payer match -------------------------------------
    # AETNA [1001] / HB AMC AETNA HMO negotiated_dollar for 36415 @ BWH = $11.17
    assert lookup.plan_rate(BWH, "36415", "AETNA [1001]") == 11.17
    assert lookup.plan_rate(BWH, "36415", "AETNA [1001]", "HB AMC AETNA HMO") == 11.17
    # payer present at this hospital+code combo but plan_name doesn't match
    # any row -> falls back to any row for that payer (per plan_rate's
    # documented fallback), still returns the payer-level rate, never None
    # just because the wrong plan string was passed.
    assert lookup.plan_rate(BWH, "36415", "AETNA [1001]", "NOT A REAL PLAN") == 11.17
    # payer absent entirely -> None
    assert lookup.plan_rate(BWH, "36415", "NONEXISTENT PAYER [0000]") is None

    # -- cross_payer_stats: 4 real commercial payers for 36415 @ BWH -------
    # source rows (negotiated_dollar): AETNA 11.17, CENTERS OF EXCELLENCE
    # 10.50, CHAMPVA 15.20, CIGNA ALTERNATE 8.53 — no government payer in
    # this sampled group, raw median 10.835 is inside the 0.2x-20x band so
    # nothing is trimmed; percentiles computed by linear interpolation.
    stats = lookup.cross_payer_stats(BWH, "36415")
    assert stats is not None
    assert stats["n_rows"] == 4
    assert stats["n_payers"] == 4
    assert stats["min"] == 8.53
    assert stats["max"] == 15.2
    assert stats["median"] == 10.84
    assert stats["p25"] == 10.01
    assert stats["p75"] == 12.18
    # The two synthetic noise rows (payer_name "NOISE TEST PAYER...", with
    # negotiated_dollar='None'/'n/a') must NOT appear as a 5th/6th payer —
    # n_payers/n_rows == 4 above (not 5 or 6) proves the TEXT/'None'-string
    # defensive parsing dropped them rather than crashing or counting them.

    assert lookup.cross_payer_stats(BWH, "00000") is None

    # -- medicare_rate: real CMS-derived rates, both components ------------
    prof = lookup.medicare_rate("99283", "professional")
    assert prof is not None
    assert prof.value == 72.74
    assert prof.component == "professional"
    assert 65 <= prof.value <= 80  # sanity gate, mirrored from scripts/fetch_medicare.py

    glob = lookup.medicare_rate("99283", "global")
    assert glob is not None
    assert glob.value == 351.63

    lab = lookup.medicare_rate("80053", "global")
    assert lab is not None
    assert lab.value == 10.56  # CLFS 2026Q3 flat national rate

    assert lookup.medicare_rate("00000", "global") is None

    # -- version() carries some identifying string, never crashes ---------
    assert isinstance(lookup.version(), str) and lookup.version()
